create table Airline
(
    id           int auto_increment
        primary key,
    name         varchar(191) not null,
    iata_code    varchar(191) null,
    headquarters varchar(191) null,
    hubs         varchar(191) null,
    country      varchar(191) null,
    logo         varchar(191) null,
    phone        varchar(191) null,
    website      varchar(191) null,
    continent    varchar(191) null
)
    collate = utf8mb4_unicode_ci;

INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (1, 'Aer Lingus', 'EI', 'Dublin, Ireland', 'Dublin Airport, Shannon Airport', 'Ireland', 'aerlingus.png', null, 'https://www.aerlingus.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (2, 'Aeroméxico', 'AM', 'Mexico City, Mexico', 'Mexico City International Airport', 'Mexico', 'aeromexico.svg', null, 'https://www.aeromexico.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (3, 'Air Asia', 'AK', 'Kuala Lumpur, Malaysia', 'Kuala Lumpur International Airport', 'Malaysia', 'airasia.webp', null, 'https://www.airasia.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (4, 'Air Canada', 'AC', 'Montreal, Quebec, Canada', 'Toronto Pearson, Vancouver, Montreal', 'Canada', 'aircanada.svg', null, 'https://www.aircanada.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (5, 'Air China', 'CA', 'Beijing, China', 'Beijing Capital International Airport', 'China', 'airchina.webp', null, 'https://www.airchina.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (6, 'Air France', 'AF', 'Tremblay-en-France, France', 'Charles de Gaulle Airport, Orly Airport', 'France', 'airfrance.svg', null, 'https://www.airfrance.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (7, 'Air India', 'AI', 'New Delhi, India', 'Indira Gandhi International Airport', 'India', 'airindia.webp', null, 'https://www.airindia.in', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (8, 'Air New Zealand', 'NZ', 'Auckland, New Zealand', 'Auckland Airport', 'New Zealand', 'airnewzealand.svg', null, 'https://www.airnewzealand.com', 'OC');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (9, 'Alaska Airlines', 'AS', 'Seattle, Washington, USA', 'Seattle-Tacoma, Portland, Anchorage, San Francisco, Los Angeles', 'USA', 'alaska.svg', null, 'https://www.alaskaair.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (10, 'All Nippon Airways', 'NH', 'Tokyo, Japan', 'Tokyo Narita, Tokyo Haneda', 'Japan', 'allnippon.svg', null, 'https://www.ana.co.jp', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (11, 'American Airlines', 'AA', 'Fort Worth, Texas, USA', 'Dallas/Fort Worth, Charlotte, Chicago-O\'Hare, Los Angeles, Miami, New York-JFK, New York-LaGuardia, Philadelphia, Phoenix, Washington-National', 'USA', 'american.webp', null, 'https://www.aa.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (12, 'Austrian Airlines', 'OS', 'Vienna, Austria', 'Vienna International Airport', 'Austria', 'austrian.svg', null, 'https://www.austrian.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (13, 'British Airways', 'BA', 'London, England', 'London Heathrow, London Gatwick', 'United Kingdom', 'british.svg', null, 'https://www.britishairways.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (14, 'Cathay Pacific', 'CX', 'Hong Kong', 'Hong Kong International Airport', 'Hong Kong', 'cathay.svg', null, 'https://www.cathaypacific.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (15, 'China Eastern', 'MU', 'Shanghai, China', 'Shanghai Pudong, Shanghai Hongqiao', 'China', 'chinaeastern.png', null, 'https://us.ceair.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (16, 'China Southern', 'CZ', 'Guangzhou, China', 'Guangzhou Baiyun International Airport', 'China', 'chinasouthern.webp', null, 'https://www.csair.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (17, 'Delta Air Lines', 'DL', 'Atlanta, Georgia, USA', 'Atlanta, Boston, Detroit, Los Angeles, Minneapolis/St. Paul, New York-JFK, New York-LaGuardia, Salt Lake City, Seattle/Tacoma', 'USA', 'delta.svg', null, 'https://www.delta.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (18, 'EasyJet', 'U2', 'Luton, England', 'London Gatwick, London Luton', 'United Kingdom', 'easyjet.svg', null, 'https://www.easyjet.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (19, 'EgyptAir', 'MS', 'Cairo, Egypt', 'Cairo International Airport', 'Egypt', 'egyptair.webp', null, 'https://www.egyptair.com', 'AF');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (20, 'Emirates', 'EK', 'Dubai, UAE', 'Dubai International Airport', 'United Arab Emirates', 'emirates.webp', null, 'https://www.emirates.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (21, 'Ethiopian Airlines', 'ET', 'Addis Ababa, Ethiopia', 'Bole International Airport', 'Ethiopia', 'ethiopian.webp', null, 'https://www.ethiopianairlines.com', 'AF');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (22, 'Eurowings', 'EW', 'Düsseldorf, Germany', 'Düsseldorf Airport, Hamburg Airport', 'Germany', 'eurowings.webp', null, 'https://www.eurowings.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (23, 'EVA Air', 'BR', 'Taoyuan, Taiwan', 'Taoyuan International Airport', 'Taiwan', 'evaair.png', null, 'https://www.evaair.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (24, 'Garuda Indonesia', 'GA', 'Jakarta, Indonesia', 'Soekarno-Hatta International Airport', 'Indonesia', 'garuda.webp', null, 'https://www.garuda-indonesia.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (25, 'Go First', 'G8', 'Mumbai, India', 'Chhatrapati Shivaji Maharaj International Airport', 'India', 'gofirst.webp', null, 'https://www.flygofirst.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (26, 'Hawaiian Airlines', 'HA', 'Honolulu, Hawaii, USA', 'Daniel K. Inouye International Airport', 'USA', 'hawaiian.webp', null, 'https://www.hawaiianairlines.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (27, 'Iberia', 'IB', 'Madrid, Spain', 'Adolfo Suárez Madrid–Barajas Airport', 'Spain', 'iberia.webp', null, 'https://www.iberia.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (28, 'IndiGo', '6E', 'Gurgaon, India', 'Indira Gandhi International Airport', 'India', 'indigo.webp', null, 'https://www.goindigo.in', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (29, 'Japan Airlines', 'JL', 'Tokyo, Japan', 'Tokyo Narita, Tokyo Haneda', 'Japan', 'japanair.webp', null, 'https://www.jal.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (30, 'Jet Airways', '9W', 'Mumbai, India', 'Chhatrapati Shivaji Maharaj International Airport', 'India', 'jetairways.webp', null, 'https://www.jetairways.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (31, 'KLM', 'KL', 'Amstelveen, Netherlands', 'Amsterdam Airport Schiphol', 'Netherlands', 'klm.webp', null, 'https://www.klm.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (32, 'Korean Air', 'KE', 'Seoul, South Korea', 'Incheon International Airport', 'South Korea', 'korean.webp', null, 'https://www.koreanair.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (33, 'LEVEL', 'LV', 'Madrid, Spain', 'Barcelona–El Prat Airport', 'Spain', 'level.svg', null, 'https://www.flylevel.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (34, 'Lufthansa', 'LH', 'Frankfurt, Germany', 'Frankfurt Airport, Munich Airport', 'Germany', 'lufthansa.webp', null, 'https://www.lufthansa.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (35, 'Malaysia Airlines', 'MH', 'Kuala Lumpur, Malaysia', 'Kuala Lumpur International Airport', 'Malaysia', 'malaysia.webp', null, 'https://www.malaysiaairlines.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (36, 'Mexicana', 'MX', 'Mexico City, Mexico', 'Mexico City International Airport', 'Mexico', 'mexicana.webp', null, 'https://www.mexicana.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (37, 'Qantas', 'QF', 'Sydney, Australia', 'Sydney Airport, Melbourne Airport', 'Australia', 'qantas.webp', null, 'https://www.qantas.com', 'OC');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (38, 'Qatar Airways', 'QR', 'Doha, Qatar', 'Hamad International Airport', 'Qatar', 'qatar.webp', null, 'https://www.qatarairways.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (39, 'Ryanair', 'FR', 'Dublin, Ireland', 'Dublin Airport, London Stansted Airport', 'Ireland', 'ryanair.webp', null, 'https://www.ryanair.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (40, 'Scandinavian Airlines', 'SK', 'Stockholm, Sweden', 'Copenhagen Airport, Oslo Airport, Stockholm Arlanda Airport', 'Sweden', 'sas.webp', null, 'https://www.flysas.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (41, 'Singapore Airlines', 'SQ', 'Singapore', 'Singapore Changi Airport', 'Singapore', 'singapore.webp', null, 'https://www.singaporeair.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (42, 'Southwest Airlines', 'WN', 'Dallas, Texas, USA', 'Atlanta, Baltimore, Chicago-Midway, Dallas-Love, Denver, Houston-Hobby, Las Vegas, Los Angeles, Oakland, Orlando, Phoenix', 'USA', 'southwest.webp', null, 'https://www.southwest.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (43, 'SpiceJet', 'SG', 'Gurgaon, India', 'Indira Gandhi International Airport', 'India', 'spicejet.webp', null, 'https://www.spicejet.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (44, 'Swiss International Air Lines', 'LX', 'Basel, Switzerland', 'Zürich Airport', 'Switzerland', 'swiss.webp', null, 'https://www.swiss.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (45, 'Turkish Airlines', 'TK', 'Istanbul, Turkey', 'Istanbul Airport', 'Turkey', 'turkish.webp', null, 'https://www.turkishairlines.com', 'EU');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (46, 'United Airlines', 'UA', 'Chicago, Illinois, USA', 'Chicago-O\'Hare, Denver, Guam, Houston-Intercontinental, Los Angeles, Newark, San Francisco, Washington-Dulles', 'USA', 'united.svg', null, 'https://www.united.com', 'NA');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (47, 'Vietnam Airlines', 'VN', 'Hanoi, Vietnam', 'Noi Bai International Airport', 'Vietnam', 'vietnam.webp', null, 'https://www.vietnamairlines.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (48, 'Vistara', 'UK', 'Gurgaon, India', 'Indira Gandhi International Airport', 'India', 'vistara.webp', null, 'https://www.airvistara.com', 'AS');
INSERT INTO restools.Airline (id, name, iata_code, headquarters, hubs, country, logo, phone, website, continent) VALUES (49, 'Wizz Air', 'W6', 'Budapest, Hungary', 'Budapest Ferenc Liszt International Airport', 'Hungary', 'wizz.png', null, 'https://wizzair.com', 'EU');
