create table Country
(
    id             int auto_increment
        primary key,
    code           varchar(191) not null,
    name           varchar(191) null,
    continent      varchar(191) null,
    wikipedia_link varchar(191) null,
    keywords       varchar(191) null,
    constraint Country_code_key
        unique (code)
)
    collate = utf8mb4_unicode_ci;

INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (1, 'AD', 'Andorra', 'EU', 'https://en.wikipedia.org/wiki/Andorra', 'Andorran airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (2, 'AE', 'United Arab Emirates', 'AS', 'https://en.wikipedia.org/wiki/United_Arab_Emirates', 'UAE,مطارات في الإمارات العربية المتحدة');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (3, 'AF', 'Afghanistan', 'AS', 'https://en.wikipedia.org/wiki/Afghanistan', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (4, 'AG', 'Antigua and Barbuda', 'NA', 'https://en.wikipedia.org/wiki/Antigua_and_Barbuda', 'Antiguan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (5, 'AI', 'Anguilla', 'NA', 'https://en.wikipedia.org/wiki/Anguilla', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (6, 'AL', 'Albania', 'EU', 'https://en.wikipedia.org/wiki/Albania', 'Albanian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (7, 'AM', 'Armenia', 'AS', 'https://en.wikipedia.org/wiki/Armenia', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (8, 'AO', 'Angola', 'AF', 'https://en.wikipedia.org/wiki/Angola', 'Angolan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (9, 'AQ', 'Antarctica', 'AN', 'https://en.wikipedia.org/wiki/Antarctica', 'Airports in Antarctica');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (10, 'AR', 'Argentina', 'SA', 'https://en.wikipedia.org/wiki/Argentina', 'Aeropuertos de Argentina');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (11, 'AS', 'American Samoa', 'OC', 'https://en.wikipedia.org/wiki/American_Samoa', 'Samoan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (12, 'AT', 'Austria', 'EU', 'https://en.wikipedia.org/wiki/Austria', 'Flughäfen in Österreich');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (13, 'AU', 'Australia', 'OC', 'https://en.wikipedia.org/wiki/Australia', 'Australian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (14, 'AW', 'Aruba', 'NA', 'https://en.wikipedia.org/wiki/Aruba', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (15, 'AZ', 'Azerbaijan', 'AS', 'https://en.wikipedia.org/wiki/Azerbaijan', 'Azerbaijani airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (16, 'BA', 'Bosnia and Herzegovina', 'EU', 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina', 'Bosnian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (17, 'BB', 'Barbados', 'NA', 'https://en.wikipedia.org/wiki/Barbados', 'Barbadan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (18, 'BD', 'Bangladesh', 'AS', 'https://en.wikipedia.org/wiki/Bangladesh', 'Bangladeshi airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (19, 'BE', 'Belgium', 'EU', 'https://en.wikipedia.org/wiki/Belgium', 'Aéroports de Belgique,Luchthavens van België');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (20, 'BF', 'Burkina Faso', 'AF', 'https://en.wikipedia.org/wiki/Burkina_Faso', 'Burkinabé airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (21, 'BG', 'Bulgaria', 'EU', 'https://en.wikipedia.org/wiki/Bulgaria', 'Bulgarian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (22, 'BH', 'Bahrain', 'AS', 'https://en.wikipedia.org/wiki/Bahrain', 'مطارات البحرين');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (23, 'BI', 'Burundi', 'AF', 'https://en.wikipedia.org/wiki/Burundi', 'Burundian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (24, 'BJ', 'Benin', 'AF', 'https://en.wikipedia.org/wiki/Benin', 'Beninese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (25, 'BL', 'Saint Barthélemy', 'NA', 'https://en.wikipedia.org/wiki/Saint_Barthélemy', 'Airports in Saint Barthélemy');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (26, 'BM', 'Bermuda', 'NA', 'https://en.wikipedia.org/wiki/Bermuda', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (27, 'BN', 'Brunei', 'AS', 'https://en.wikipedia.org/wiki/Brunei', 'Bruneian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (28, 'BO', 'Bolivia', 'SA', 'https://en.wikipedia.org/wiki/Bolivia', 'Aeropuertos de Bolivia');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (29, 'BQ', 'Caribbean Netherlands', 'NA', 'https://en.wikipedia.org/wiki/Caribbean_Netherlands', 'Airports in Caribbean Netherlands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (30, 'BR', 'Brazil', 'SA', 'https://en.wikipedia.org/wiki/Brazil', 'Brasil, Brasilian, Aeroportos do Brasil');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (31, 'BS', 'Bahamas', 'NA', 'https://en.wikipedia.org/wiki/Bahamas', 'Bahaman airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (32, 'BT', 'Bhutan', 'AS', 'https://en.wikipedia.org/wiki/Bhutan', 'Bhutanese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (33, 'BW', 'Botswana', 'AF', 'https://en.wikipedia.org/wiki/Botswana', 'Botswana airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (34, 'BY', 'Belarus', 'EU', 'https://en.wikipedia.org/wiki/Belarus', 'Belarussian, Беларусь');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (35, 'BZ', 'Belize', 'NA', 'https://en.wikipedia.org/wiki/Belize', 'Belizean airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (36, 'CA', 'Canada', 'NA', 'https://en.wikipedia.org/wiki/Canada', 'Canadian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (37, 'CC', 'Cocos (Keeling) Islands', 'AS', 'https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands', 'Airports in Cocos (Keeling) Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (38, 'CD', 'Democratic Republic of the Congo', 'AF', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo', 'DRC');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (39, 'CF', 'Central African Republic', 'AF', 'https://en.wikipedia.org/wiki/Central_African_Republic', 'Airports in Central African Republic');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (40, 'CG', 'Republic of the Congo', 'AF', 'https://en.wikipedia.org/wiki/Republic_of_the_Congo', 'Congo-Brazzaville');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (41, 'CH', 'Switzerland', 'EU', 'https://en.wikipedia.org/wiki/Switzerland', 'Aéroports de la Suisse,Flughäfen der Schweiz');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (42, 'CI', 'Côte d\'Ivoire', 'AF', 'https://en.wikipedia.org/wiki/Côte_d\'Ivoire', 'Ivory Coast');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (43, 'CK', 'Cook Islands', 'OC', 'https://en.wikipedia.org/wiki/Cook_Islands', 'Airports in Cook Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (44, 'CL', 'Chile', 'SA', 'https://en.wikipedia.org/wiki/Chile', 'Aeropuertos de Chile');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (45, 'CM', 'Cameroon', 'AF', 'https://en.wikipedia.org/wiki/Cameroon', 'Cameroonian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (46, 'CN', 'China', 'AS', 'https://en.wikipedia.org/wiki/China', '中国的机场');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (47, 'CO', 'Colombia', 'SA', 'https://en.wikipedia.org/wiki/Colombia', 'Aeropuertos de Colombia');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (48, 'CR', 'Costa Rica', 'NA', 'https://en.wikipedia.org/wiki/Costa_Rica', 'Aeropuertos de Costa Rica');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (49, 'CU', 'Cuba', 'NA', 'https://en.wikipedia.org/wiki/Cuba', 'Aeropuertos de Cuba');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (50, 'CV', 'Cape Verde', 'AF', 'https://en.wikipedia.org/wiki/Cape_Verde', 'Airports in Cape Verde');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (51, 'CW', 'Curaçao', 'NA', 'https://en.wikipedia.org/wiki/Cura%C3%A7ao', 'Airports in Curaçao');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (52, 'CX', 'Christmas Island', 'AS', 'https://en.wikipedia.org/wiki/Christmas_Island', 'Airports in Christmas Island');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (53, 'CY', 'Cyprus', 'AS', 'https://en.wikipedia.org/wiki/Cyprus', 'Cypriot airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (54, 'CZ', 'Czech Republic', 'EU', 'https://en.wikipedia.org/wiki/Czech_Republic', 'Letiště České republiky, Czechia');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (55, 'DE', 'Germany', 'EU', 'https://en.wikipedia.org/wiki/Germany', 'Flughäfen in Deutschland');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (56, 'DJ', 'Djibouti', 'AF', 'https://en.wikipedia.org/wiki/Djibouti', 'Djiboutian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (57, 'DK', 'Denmark', 'EU', 'https://en.wikipedia.org/wiki/Denmark', 'Lufthavnene i Danmark');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (58, 'DM', 'Dominica', 'NA', 'https://en.wikipedia.org/wiki/Dominica', 'Airports in Dominica');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (59, 'DO', 'Dominican Republic', 'NA', 'https://en.wikipedia.org/wiki/Dominican_Republic', 'Airports in Dominican Republic');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (60, 'DZ', 'Algeria', 'AF', 'https://en.wikipedia.org/wiki/Algeria', 'مطارات الجزائر');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (61, 'EC', 'Ecuador', 'SA', 'https://en.wikipedia.org/wiki/Ecuador', 'Aeropuertos de Ecuador');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (62, 'EE', 'Estonia', 'EU', 'https://en.wikipedia.org/wiki/Estonia', 'Estonian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (63, 'EG', 'Egypt', 'AF', 'https://en.wikipedia.org/wiki/Egypt', 'مطارات مصر, Egyptian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (64, 'EH', 'Western Sahara', 'AF', 'https://en.wikipedia.org/wiki/Western_Sahara', 'Sahrawian, مطارات الصحراء الغربية');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (65, 'ER', 'Eritrea', 'AF', 'https://en.wikipedia.org/wiki/Eritrea', 'Eritrean airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (66, 'ES', 'Spain', 'EU', 'https://en.wikipedia.org/wiki/Spain', 'Aeropuertos de España');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (67, 'ET', 'Ethiopia', 'AF', 'https://en.wikipedia.org/wiki/Ethiopia', 'Ethiopian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (68, 'FI', 'Finland', 'EU', 'https://en.wikipedia.org/wiki/Finland', 'Lentokentät, Suomen');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (69, 'FJ', 'Fiji', 'OC', 'https://en.wikipedia.org/wiki/Fiji', 'Fijan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (70, 'FK', 'Falkland Islands', 'SA', 'https://en.wikipedia.org/wiki/Falkland_Islands', 'Airports in Falkland Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (71, 'FM', 'Micronesia', 'OC', 'https://en.wikipedia.org/wiki/Federated_States_of_Micronesia', 'Micronesian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (72, 'FO', 'Faroe Islands', 'EU', 'https://en.wikipedia.org/wiki/Faroe_Islands', 'Faroese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (73, 'FR', 'France', 'EU', 'https://en.wikipedia.org/wiki/France', 'Aéroports de France');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (74, 'GA', 'Gabon', 'AF', 'https://en.wikipedia.org/wiki/Gabon', 'Gabonese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (75, 'GB', 'United Kingdom', 'EU', 'https://en.wikipedia.org/wiki/United_Kingdom', 'Great Britain');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (76, 'GD', 'Grenada', 'NA', 'https://en.wikipedia.org/wiki/Grenada', 'Grenadian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (77, 'GE', 'Georgia', 'AS', 'https://en.wikipedia.org/wiki/Georgia_(country)', 'Georgian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (78, 'GF', 'French Guiana', 'SA', 'https://en.wikipedia.org/wiki/French_Guiana', 'French Guyana');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (79, 'GG', 'Guernsey', 'EU', 'https://en.wikipedia.org/wiki/Guernsey', 'Airports in Guernsey');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (80, 'GH', 'Ghana', 'AF', 'https://en.wikipedia.org/wiki/Ghana', 'Ghanan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (81, 'GI', 'Gibraltar', 'EU', 'https://en.wikipedia.org/wiki/Gibraltar', 'Gibraltarian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (82, 'GL', 'Greenland', 'NA', 'https://en.wikipedia.org/wiki/Greenland', 'Airports in Greenland');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (83, 'GM', 'Gambia', 'AF', 'https://en.wikipedia.org/wiki/Gambia', 'Gambian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (84, 'GN', 'Guinea', 'AF', 'https://en.wikipedia.org/wiki/Guinea', 'Aéroports de la Guinée');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (85, 'GP', 'Guadeloupe', 'NA', 'https://en.wikipedia.org/wiki/Guadeloupe', 'Airports in Guadeloupe');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (86, 'GQ', 'Equatorial Guinea', 'AF', 'https://en.wikipedia.org/wiki/Equatorial_Guinea', 'Airports in Equatorial Guinea');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (87, 'GR', 'Greece', 'EU', 'https://en.wikipedia.org/wiki/Greece', 'αεροδρόμια στην Ελλάδα');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (88, 'GS', 'South Georgia and the South Sandwich Islands', 'AN', 'https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands', 'Airports in South Georgia and the South Sandwich Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (89, 'GT', 'Guatemala', 'NA', 'https://en.wikipedia.org/wiki/Guatemala', 'Aeropuertos de Guatemala');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (90, 'GU', 'Guam', 'OC', 'https://en.wikipedia.org/wiki/Guam', 'Guamanian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (91, 'GW', 'Guinea-Bissau', 'AF', 'https://en.wikipedia.org/wiki/Guinea-Bissau', 'Airports in Guinea-Bissau');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (92, 'GY', 'Guyana', 'SA', 'https://en.wikipedia.org/wiki/Guyana', 'Guyanese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (93, 'HK', 'Hong Kong', 'AS', 'https://en.wikipedia.org/wiki/Hong_Kong', 'Airports in Hong Kong');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (94, 'HM', 'Heard and McDonald Islands', 'OC', 'https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands', 'Airports in Heard and McDonald Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (95, 'HN', 'Honduras', 'NA', 'https://en.wikipedia.org/wiki/Honduras', 'Aeropuertos de Honduras');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (96, 'HR', 'Croatia', 'EU', 'https://en.wikipedia.org/wiki/Croatia', 'Croatian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (97, 'HT', 'Haiti', 'NA', 'https://en.wikipedia.org/wiki/Haiti', 'Aéroports de Haïti');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (98, 'HU', 'Hungary', 'EU', 'https://en.wikipedia.org/wiki/Hungary', 'Repülőterek Magyarország');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (99, 'ID', 'Indonesia', 'AS', 'https://en.wikipedia.org/wiki/Indonesia', 'Bandara di Indonesia');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (100, 'IE', 'Ireland', 'EU', 'https://en.wikipedia.org/wiki/Ireland', 'Eire');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (101, 'IL', 'Israel', 'AS', 'https://en.wikipedia.org/wiki/Israel', 'שדות התעופה של ישראל');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (102, 'IM', 'Isle of Man', 'EU', 'https://en.wikipedia.org/wiki/Isle_of_Man', 'Manx');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (103, 'IN', 'India', 'AS', 'https://en.wikipedia.org/wiki/India', 'Airports in India, Indian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (104, 'IO', 'British Indian Ocean Territory', 'AS', 'https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory', 'Airports in British Indian Ocean Territory');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (105, 'IQ', 'Iraq', 'AS', 'https://en.wikipedia.org/wiki/Iraq', 'مطارات العراق');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (106, 'IR', 'Iran', 'AS', 'https://en.wikipedia.org/wiki/Iran', 'فرودگاه های ایران');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (107, 'IS', 'Iceland', 'EU', 'https://en.wikipedia.org/wiki/Iceland', 'Icelandic airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (108, 'IT', 'Italy', 'EU', 'https://en.wikipedia.org/wiki/Italy', 'Aeroporti d\'Italia');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (109, 'JE', 'Jersey', 'EU', 'https://en.wikipedia.org/wiki/Jersey', 'Airports in Jersey');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (110, 'JM', 'Jamaica', 'NA', 'https://en.wikipedia.org/wiki/Jamaica', 'Jamaican airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (111, 'JO', 'Jordan', 'AS', 'https://en.wikipedia.org/wiki/Jordan', 'مطارات في الأردن');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (112, 'JP', 'Japan', 'AS', 'https://en.wikipedia.org/wiki/Japan', 'Nippon, 日本の空港');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (113, 'KE', 'Kenya', 'AF', 'https://en.wikipedia.org/wiki/Kenya', 'Kenyan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (114, 'KG', 'Kyrgyzstan', 'AS', 'https://en.wikipedia.org/wiki/Kyrgyzstan', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (115, 'KH', 'Cambodia', 'AS', 'https://en.wikipedia.org/wiki/Cambodia', 'Cambodian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (116, 'KI', 'Kiribati', 'OC', 'https://en.wikipedia.org/wiki/Kiribati', 'Airports in Kiribati');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (117, 'KM', 'Comoros', 'AF', 'https://en.wikipedia.org/wiki/Comoros', 'جزر القمر');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (118, 'KN', 'Saint Kitts and Nevis', 'NA', 'https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis', 'Airports in Saint Kitts and Nevis');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (119, 'KP', 'North Korea', 'AS', 'https://en.wikipedia.org/wiki/North_Korea', 'North Korean airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (120, 'KR', 'South Korea', 'AS', 'https://en.wikipedia.org/wiki/South_Korea', '한국의 공항');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (121, 'KW', 'Kuwait', 'AS', 'https://en.wikipedia.org/wiki/Kuwait', 'Kuwaiti airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (122, 'KY', 'Cayman Islands', 'NA', 'https://en.wikipedia.org/wiki/Cayman_Islands', 'Airports in Cayman Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (123, 'KZ', 'Kazakhstan', 'AS', 'https://en.wikipedia.org/wiki/Kazakhstan', 'Kazakh');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (124, 'LA', 'Laos', 'AS', 'https://en.wikipedia.org/wiki/Laos', 'Laotian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (125, 'LB', 'Lebanon', 'AS', 'https://en.wikipedia.org/wiki/Lebanon', 'المطارات في لبنان');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (126, 'LC', 'Saint Lucia', 'NA', 'https://en.wikipedia.org/wiki/Saint_Lucia', 'Airports in Saint Lucia');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (127, 'LI', 'Liechtenstein', 'EU', 'https://en.wikipedia.org/wiki/Liechtenstein', 'Airports in Liechtenstein');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (128, 'LK', 'Sri Lanka', 'AS', 'https://en.wikipedia.org/wiki/Sri_Lanka', 'Sri Lankan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (129, 'LR', 'Liberia', 'AF', 'https://en.wikipedia.org/wiki/Liberia', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (130, 'LS', 'Lesotho', 'AF', 'https://en.wikipedia.org/wiki/Lesotho', 'Airports in Lesotho');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (131, 'LT', 'Lithuania', 'EU', 'https://en.wikipedia.org/wiki/Lithuania', 'Lithuanian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (132, 'LU', 'Luxembourg', 'EU', 'https://en.wikipedia.org/wiki/Luxembourg', 'Airports in Luxembourg');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (133, 'LV', 'Latvia', 'EU', 'https://en.wikipedia.org/wiki/Latvia', 'Latvian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (134, 'LY', 'Libya', 'AF', 'https://en.wikipedia.org/wiki/Libya', 'مطارات في ليبيا');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (135, 'MA', 'Morocco', 'AF', 'https://en.wikipedia.org/wiki/Morocco', 'مطارات المغرب');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (136, 'MC', 'Monaco', 'EU', 'https://en.wikipedia.org/wiki/Monaco', 'Airports in Monaco');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (137, 'MD', 'Moldova', 'EU', 'https://en.wikipedia.org/wiki/Moldova', 'Airports in Moldova');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (138, 'ME', 'Montenegro', 'EU', 'https://en.wikipedia.org/wiki/Montenegro', 'Montenegran airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (139, 'MF', 'Saint Martin', 'NA', 'https://en.wikipedia.org/wiki/Saint_Martin_(France)', 'Airports in Saint Martin');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (140, 'MG', 'Madagascar', 'AF', 'https://en.wikipedia.org/wiki/Madagascar', 'Airports in Madagascar');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (141, 'MH', 'Marshall Islands', 'OC', 'https://en.wikipedia.org/wiki/Marshall_Islands', 'Airports in Marshall Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (142, 'MK', 'North Macedonia', 'EU', 'https://en.wikipedia.org/wiki/Macedonia', 'Macedonian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (143, 'ML', 'Mali', 'AF', 'https://en.wikipedia.org/wiki/Mali', 'Aéroports du Mali, Malian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (144, 'MM', 'Myanmar', 'AS', 'https://en.wikipedia.org/wiki/Burma', 'Myanmar');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (145, 'MN', 'Mongolia', 'AS', 'https://en.wikipedia.org/wiki/Mongolia', 'Mongolian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (146, 'MO', 'Macau', 'AS', 'https://en.wikipedia.org/wiki/Macau', 'Macao');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (147, 'MP', 'Northern Mariana Islands', 'OC', 'https://en.wikipedia.org/wiki/Northern_Mariana_Islands', 'Airports in Northern Mariana Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (148, 'MQ', 'Martinique', 'NA', 'https://en.wikipedia.org/wiki/Martinique', 'Airports in Martinique');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (149, 'MR', 'Mauritania', 'AF', 'https://en.wikipedia.org/wiki/Mauritania', 'مطارات موريتانيا');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (150, 'MS', 'Montserrat', 'NA', 'https://en.wikipedia.org/wiki/Montserrat', 'Airports in Montserrat');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (151, 'MT', 'Malta', 'EU', 'https://en.wikipedia.org/wiki/Malta', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (152, 'MU', 'Mauritius', 'AF', 'https://en.wikipedia.org/wiki/Mauritius', 'Airports in Mauritius');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (153, 'MV', 'Maldives', 'AS', 'https://en.wikipedia.org/wiki/Maldives', 'Airports in Maldives');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (154, 'MW', 'Malawi', 'AF', 'https://en.wikipedia.org/wiki/Malawi', 'Airports in Malawi');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (155, 'MX', 'Mexico', 'NA', 'https://en.wikipedia.org/wiki/Mexico', 'Aeropuertos de México, Mexican airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (156, 'MY', 'Malaysia', 'AS', 'https://en.wikipedia.org/wiki/Malaysia', 'Lapangan Terbang Malaysia');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (157, 'MZ', 'Mozambique', 'AF', 'https://en.wikipedia.org/wiki/Mozambique', 'Airports in Mozambique');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (158, 'NA', 'Namibia', 'AF', 'https://en.wikipedia.org/wiki/Namibia', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (159, 'NC', 'New Caledonia', 'OC', 'https://en.wikipedia.org/wiki/New_Caledonia', 'Airports in New Caledonia');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (160, 'NE', 'Niger', 'AF', 'https://en.wikipedia.org/wiki/Niger', 'Nigerien airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (161, 'NF', 'Norfolk Island', 'OC', 'https://en.wikipedia.org/wiki/Norfolk_Island', 'Airports in Norfolk Island');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (162, 'NG', 'Nigeria', 'AF', 'https://en.wikipedia.org/wiki/Nigeria', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (163, 'NI', 'Nicaragua', 'NA', 'https://en.wikipedia.org/wiki/Nicaragua', 'Aeropuertos de Nicaragua');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (164, 'NL', 'Netherlands', 'EU', 'https://en.wikipedia.org/wiki/Netherlands', 'Holland, Luchthavens van Nederland, Dutch airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (165, 'NO', 'Norway', 'EU', 'https://en.wikipedia.org/wiki/Norway', 'Flyplasser i Norge');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (166, 'NP', 'Nepal', 'AS', 'https://en.wikipedia.org/wiki/Nepal', 'नेपाल विमानस्थलको');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (167, 'NR', 'Nauru', 'OC', 'https://en.wikipedia.org/wiki/Nauru', 'Airports in Nauru');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (168, 'NU', 'Niue', 'OC', 'https://en.wikipedia.org/wiki/Niue', 'Niuean airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (169, 'NZ', 'New Zealand', 'OC', 'https://en.wikipedia.org/wiki/New_Zealand', 'Airports in New Zealand');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (170, 'OM', 'Oman', 'AS', 'https://en.wikipedia.org/wiki/Oman', 'مطارات عمان');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (171, 'PA', 'Panama', 'NA', 'https://en.wikipedia.org/wiki/Panama', 'Aeropuertos de Panamá');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (172, 'PE', 'Peru', 'SA', 'https://en.wikipedia.org/wiki/Perú', 'Aeropuertos de Perú');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (173, 'PF', 'French Polynesia', 'OC', 'https://en.wikipedia.org/wiki/French_Polynesia', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (174, 'PG', 'Papua New Guinea', 'OC', 'https://en.wikipedia.org/wiki/Papua_New_Guinea', 'Airports in Papua New Guinea');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (175, 'PH', 'Philippines', 'AS', 'https://en.wikipedia.org/wiki/Philippines', 'Mga alternatibong byahe mula sa Pilipinas');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (176, 'PK', 'Pakistan', 'AS', 'https://en.wikipedia.org/wiki/Pakistan', 'پاکستان کے ہوائی اڈوں');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (177, 'PL', 'Poland', 'EU', 'https://en.wikipedia.org/wiki/Poland', 'Lotniska Polski');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (178, 'PM', 'Saint Pierre and Miquelon', 'NA', 'https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon', 'Airports in Saint Pierre and Miquelon');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (179, 'PN', 'Pitcairn', 'OC', 'https://en.wikipedia.org/wiki/Pitcairn', 'Airports in Pitcairn');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (180, 'PR', 'Puerto Rico', 'NA', 'https://en.wikipedia.org/wiki/Puerto_Rico', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (181, 'PS', 'Palestinian Territory', 'AS', 'https://en.wikipedia.org/wiki/Palestinian_Territory', 'Palestinian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (182, 'PT', 'Portugal', 'EU', 'https://en.wikipedia.org/wiki/Portugal', 'Aeroportos de Portugal');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (183, 'PW', 'Palau', 'OC', 'https://en.wikipedia.org/wiki/Palau', 'Palauan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (184, 'PY', 'Paraguay', 'SA', 'https://en.wikipedia.org/wiki/Paraguay', 'Aeropuertos de Paraguay');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (185, 'QA', 'Qatar', 'AS', 'https://en.wikipedia.org/wiki/Qatar', 'مطارات قطر');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (186, 'RE', 'Réunion', 'AF', 'https://en.wikipedia.org/wiki/Réunion', 'Île Bourbon, La Réunion');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (187, 'RO', 'Romania', 'EU', 'https://en.wikipedia.org/wiki/Romania', 'Aeroporturi din România');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (188, 'RS', 'Serbia', 'EU', 'https://en.wikipedia.org/wiki/Serbia', 'Serb');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (189, 'RU', 'Russia', 'EU', 'https://en.wikipedia.org/wiki/Russia', 'Soviet, Sovietskaya, Sovetskaya, Аэропорты России');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (190, 'RW', 'Rwanda', 'AF', 'https://en.wikipedia.org/wiki/Rwanda', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (191, 'SA', 'Saudi Arabia', 'AS', 'https://en.wikipedia.org/wiki/Saudi_Arabia', 'مطارات المملكة العربية السعودية,المطارات لموسم الحج');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (192, 'SB', 'Solomon Islands', 'OC', 'https://en.wikipedia.org/wiki/Solomon_Islands', 'Airports in Solomon Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (193, 'SC', 'Seychelles', 'AF', 'https://en.wikipedia.org/wiki/Seychelles', 'Airports in Seychelles');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (194, 'SD', 'Sudan', 'AF', 'https://en.wikipedia.org/wiki/Sudan', 'مطارات السودان');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (195, 'SE', 'Sweden', 'EU', 'https://en.wikipedia.org/wiki/Sweden', 'Flygplatserna, Sverige');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (196, 'SG', 'Singapore', 'AS', 'https://en.wikipedia.org/wiki/Singapore', 'Singaporean airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (197, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'AF', 'https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha', 'Airports in Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (198, 'SI', 'Slovenia', 'EU', 'https://en.wikipedia.org/wiki/Slovenia', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (199, 'SK', 'Slovakia', 'EU', 'https://en.wikipedia.org/wiki/Slovakia', 'letisko Slovenska');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (200, 'SL', 'Sierra Leone', 'AF', 'https://en.wikipedia.org/wiki/Sierra_Leone', 'Sierra Leonean airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (201, 'SM', 'San Marino', 'EU', 'https://en.wikipedia.org/wiki/San_Marino', 'Airports in San Marino');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (202, 'SN', 'Senegal', 'AF', 'https://en.wikipedia.org/wiki/Senegal', 'Aéroports du Sénégal, Senegalese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (203, 'SO', 'Somalia', 'AF', 'https://en.wikipedia.org/wiki/Somalia', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (204, 'SR', 'Suriname', 'SA', 'https://en.wikipedia.org/wiki/Suriname', 'Surinamese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (205, 'SS', 'South Sudan', 'AF', 'https://en.wikipedia.org/wiki/South_Sudan', 'South Sudanese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (206, 'ST', 'São Tomé and Principe', 'AF', 'https://en.wikipedia.org/wiki/São_Tomé_and_Principe', 'Airports in São Tomé and Principe');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (207, 'SV', 'El Salvador', 'NA', 'https://en.wikipedia.org/wiki/El_Salvador', 'Salvadorian, Salvadorean');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (208, 'SX', 'Sint Maarten', 'NA', 'https://en.wikipedia.org/wiki/Sint_Maarten', 'Airports in Sint Maarten');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (209, 'SY', 'Syria', 'AS', 'https://en.wikipedia.org/wiki/Syria', 'مطارات سوريا');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (210, 'SZ', 'Eswatini', 'AF', 'https://en.wikipedia.org/wiki/Eswatini', 'Swaziland');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (211, 'TC', 'Turks and Caicos Islands', 'NA', 'https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands', 'Airports in Turks and Caicos Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (212, 'TD', 'Chad', 'AF', 'https://en.wikipedia.org/wiki/Chad', 'Airports in Chad');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (213, 'TF', 'French Southern and Antarctic Lands', 'AF', 'https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands', 'Airports in French Southern and Antarctic Lands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (214, 'TG', 'Togo', 'AF', 'https://en.wikipedia.org/wiki/Togo', 'Airports in Togo');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (215, 'TH', 'Thailand', 'AS', 'https://en.wikipedia.org/wiki/Thailand', 'Siam, Siamese');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (216, 'TJ', 'Tajikistan', 'AS', 'https://en.wikipedia.org/wiki/Tajikistan', 'Tajik');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (217, 'TK', 'Tokelau', 'OC', 'https://en.wikipedia.org/wiki/Tokelau', 'Airports in Tokelau');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (218, 'TL', 'Timor-Leste', 'AS', 'https://en.wikipedia.org/wiki/Timor-Leste', 'East Timor');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (219, 'TM', 'Turkmenistan', 'AS', 'https://en.wikipedia.org/wiki/Turkmenistan', 'Turkmenistani airports, Airports in Turkmenistan');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (220, 'TN', 'Tunisia', 'AF', 'https://en.wikipedia.org/wiki/Tunisia', 'مطارات تونس');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (221, 'TO', 'Tonga', 'OC', 'https://en.wikipedia.org/wiki/Tonga', 'Airports in Tonga');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (222, 'TR', 'Turkey', 'AS', 'https://en.wikipedia.org/wiki/Turkey', 'Türkiye havaalanları');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (223, 'TT', 'Trinidad and Tobago', 'NA', 'https://en.wikipedia.org/wiki/Trinidad_and_Tobago', 'Airports in Trinidad and Tobago');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (224, 'TV', 'Tuvalu', 'OC', 'https://en.wikipedia.org/wiki/Tuvalu', 'Airports in Tuvalu');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (225, 'TW', 'Taiwan', 'AS', 'https://en.wikipedia.org/wiki/Taiwan', 'Taiwanese airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (226, 'TZ', 'Tanzania', 'AF', 'https://en.wikipedia.org/wiki/Tanzania', 'Tanzanian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (227, 'UA', 'Ukraine', 'EU', 'https://en.wikipedia.org/wiki/Ukraine', 'Аеропорти України');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (228, 'UG', 'Uganda', 'AF', 'https://en.wikipedia.org/wiki/Uganda', null);
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (229, 'UM', 'United States Minor Outlying Islands', 'OC', 'https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands', 'Airports in United States Minor Outlying Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (230, 'US', 'United States', 'NA', 'https://en.wikipedia.org/wiki/United_States', 'American airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (231, 'UY', 'Uruguay', 'SA', 'https://en.wikipedia.org/wiki/Uruguay', 'Aeropuertos de Uruguay');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (232, 'UZ', 'Uzbekistan', 'AS', 'https://en.wikipedia.org/wiki/Uzbekistan', 'Uzbek');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (233, 'VA', 'Vatican City', 'EU', 'https://en.wikipedia.org/wiki/Vatican_City', 'The Holy See');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (234, 'VC', 'Saint Vincent and the Grenadines', 'NA', 'https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines', 'Airports in Saint Vincent and the Grenadines');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (235, 'VE', 'Venezuela', 'SA', 'https://en.wikipedia.org/wiki/Venezuela', 'Aeropuertos de Venezuela');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (236, 'VG', 'British Virgin Islands', 'NA', 'https://en.wikipedia.org/wiki/British_Virgin_Islands', 'Airports in British Virgin Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (237, 'VI', 'U.S. Virgin Islands', 'NA', 'https://en.wikipedia.org/wiki/U.S._Virgin_Islands', 'Airports in U.S. Virgin Islands');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (238, 'VN', 'Vietnam', 'AS', 'https://en.wikipedia.org/wiki/Vietnam', 'Các sân bay của Việt Nam');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (239, 'VU', 'Vanuatu', 'OC', 'https://en.wikipedia.org/wiki/Vanuatu', 'Airports in Vanuatu');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (240, 'WF', 'Wallis and Futuna', 'OC', 'https://en.wikipedia.org/wiki/Wallis_and_Futuna', 'Airports in Wallis and Futuna');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (241, 'WS', 'Samoa', 'OC', 'https://en.wikipedia.org/wiki/Samoa', 'Samoan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (242, 'XK', 'Kosovo', 'EU', 'https://en.wikipedia.org/wiki/Kosovo', 'Kosova');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (243, 'YE', 'Yemen', 'AS', 'https://en.wikipedia.org/wiki/Yemen', 'مطارات اليمن');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (244, 'YT', 'Mayotte', 'AF', 'https://en.wikipedia.org/wiki/Mayotte', 'Airports in Mayotte');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (245, 'ZA', 'South Africa', 'AF', 'https://en.wikipedia.org/wiki/South_Africa', 'South African airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (246, 'ZM', 'Zambia', 'AF', 'https://en.wikipedia.org/wiki/Zambia', 'Zambian airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (247, 'ZW', 'Zimbabwe', 'AF', 'https://en.wikipedia.org/wiki/Zimbabwe', 'Zimbabwan airports');
INSERT INTO restools.Country (id, code, name, continent, wikipedia_link, keywords) VALUES (248, 'ZZ', 'Unknown or unassigned country', 'AF', 'https://en.wikipedia.org/wiki/Unknown_or_unassigned_country', 'Airports in Unknown or unassigned country');
