@echo off
echo Installing dependencies...
npm install csv-parse ts-node typescript @types/node @prisma/client --legacy-peer-deps
echo Generating Prisma client...
npx prisma generate
echo Loading aviation data from GitHub...
cd scripts && npx ts-node -P tsconfig.json Load_Airport_Data.ts && cd ..
echo Done.
